### ISSUE TITLE
Invalid character in header content ["Content-disposition"]

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/etherpad_mypads_ynh#109]
When used with libreto user often used special char in pad name.

We have around 3000 pads and we experiments some issues with markdown export:
```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-disposition"]
    at ServerResponse.setHeader (_http_outgoing.js:473:3)
    at /var/www/etherpad_mypads/node_modules/ep_markdown/express.js:9:11
    at /var/www/etherpad_mypads/node_modules/ep_markdown/exportMarkdown.js:427:5
    at /var/www/etherpad_mypads/node_modules/ep_markdown/exportMarkdown.js:59:5
    at /var/www/etherpad_mypads/node_modules/ep_markdown/exportMarkdown.js:52:5
    at fn (/var/www/etherpad_mypads/src/node_modules/async/lib/async.js:641:34)
    at Immediate.<anonymous> (/var/www/etherpad_mypads/src/node_modules/async/lib/async.js:557:34)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

It seems Content-disposition contains a filename generated from pad name.

**Comment by zamentur** [comment]
I see also this error, but i am not sure it's related...

Database is not configured with charset utf8mb4 -- This may lead to crashes when certain characters are pasted in pads

I have some pad with spanish char...

**Comment by zamentur** [comment]
The bug has been fixed on the module upstream. So we just need to be up to date
