### ISSUE TITLE
Can't install new plugins

### ISSUE THREAD

**Issue by mic-rigaud** [YunoHost-Apps/etherpad_mypads_ynh#39]
Hello,

I have a problem with the last version of etherpad. When i try to add plugins that doesn't work. I don't understand why. (with the previous version i didn't have this problem)
I can click on install in the plugin admin interface. But it is still on "installing" after few minutes if i actualise the page the plugin disappears.

Thank you for your help

etherpad version : 1.6.5~ynh2
yunohost version: 2.7.12 (stable)

**Comment by maniackcrudelis** [comment]
Hello

I reproduce, maybe not yours, but still an error when I try to install a plugin from the admin interface.
Could you have a look to your log `/var/log/etherpad_mypads/etherpad.log`?
Mine says
```
[ERROR] console - SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/etherpad_mypads/src/node_modules/npm/lib/install.js:109:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```
as soon as I try to install a plugin.

**Comment by mic-rigaud** [comment]
Hello,

It is exactly the same error for me.

**Comment by maniackcrudelis** [comment]
OK, I think then it would be an error from Etherpad.
I'm going to open an issue in their repository.

**Comment by anmol26s** [comment]
Any update on it?

**Comment by maniackcrudelis** [comment]
As you can see [here](https://github.com/ether/etherpad-lite/issues/3401), no news since June, 6.

**Comment by anmol26s** [comment]
:(

**Comment by SiM** [comment]
After the recent upgrade, I can now install plugins again, thanks ! :tada:
